target 'Reminder' do
    platform :osx, '10.12'
    # GTMAppAuth is now written in Swift, so need this to build.
    use_frameworks!
    pod 'GoogleAPIClientForREST/Calendar'
    pod 'GTMAppAuth', '>= 3.0'
    pod 'AppAuth'
end